# 🌳 Decision Tree & 🌲 Random Forest

# Decision Tree = A Machine Learning model that makes predictions by asking a sequence of questions and following branches to reach a final answer.

          Credit History?
           /           \
         Good          Bad
          /              \
     Income > 5000?      Reject
       /      \
     Yes       No
     /          \
 Approve       Reject


 Isliye Decision Tree ko tum machine learning ka smart IF-ELSE system samajh sakte ho.

| Term              | Meaning                              |
| ----------------- | ------------------------------------ |
| **Root Node**     | The first question                   |
| **Decision Node** | A question/condition inside the tree |
| **Branch**        | The path taken after a condition     |
| **Leaf Node**     | The final prediction                 |
| **Depth**         | How many levels the tree has         |

In [ ]:
import pandas as pd 
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score 
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [3]:
df = pd.read_csv("S:\Github\machine learinng\loan_dataset.csv")
df.head()

<>:1: SyntaxWarning: invalid escape sequence '\G'
<>:1: SyntaxWarning: invalid escape sequence '\G'
C:\Users\DELL\AppData\Local\Temp\ipykernel_14292\1480769548.py:1: SyntaxWarning: invalid escape sequence '\G'
  df = pd.read_csv("S:\Github\machine learinng\loan_dataset.csv")

  Loan_ID  Gender Married  ...  Credit_History Property_Area Loan_Status
0   LP001    Male     Yes  ...               1         Urban           Y
1   LP002  Female      No  ...               1         Rural           N
2   LP003    Male     Yes  ...               1         Urban           Y
3   LP004    Male     Yes  ...               1         Urban           Y
4   LP005    Male      No  ...               1         Urban           Y

[5 rows x 13 columns]

In [12]:
X = df.drop("Loan_Status", axis =1)
y = df["Loan_Status"]

In [11]:
df.drop("Loan_ID", axis=1)

    Gender Married  Dependents  ... Credit_History Property_Area  Loan_Status
0     Male     Yes           0  ...              1         Urban            Y
1   Female      No           1  ...              1         Rural            N
2     Male     Yes           0  ...              1         Urban            Y
3     Male     Yes           0  ...              1         Urban            Y
4     Male      No           0  ...              1         Urban            Y
5     Male     Yes           2  ...              1         Urban            Y
6   Female      No           0  ...              1         Rural            N
7     Male     Yes           3  ...              0     Semiurban            N
8     Male     Yes           2  ...              1     Semiurban            Y
9   Female      No           0  ...              1         Urban            Y
10    Male     Yes           1  ...              1         Rural            Y
11  Female      No           0  ...              1         Urban            Y
12    Male     Yes           0  ...              1         Rural            N
13    Male     Yes           2  ...              1     Semiurban            Y
14  Female     Yes           0  ...              1         Urban            Y
15    Male      No           0  ...              0         Rural            N
16    Male     Yes           1  ...              1     Semiurban            Y
17  Female      No           0  ...              1         Rural            N
18    Male     Yes           3  ...              1         Urban            Y
19    Male     Yes           0  ...              1         Urban            Y
20  Female     Yes           1  ...              1     Semiurban            Y
21    Male      No           2  ...              0         Rural            N
22    Male     Yes           0  ...              1         Urban            Y
23  Female      No           0  ...              1     Semiurban            Y
24    Male     Yes           1  ...              1         Rural            N
25    Male     Yes           2  ...              1         Urban            Y
26  Female      No           0  ...              1     Semiurban            Y
27    Male     Yes           3  ...              1         Rural            Y
28    Male      No           0  ...              0         Rural            N
29  Female     Yes           1  ...              1         Urban            Y

[30 rows x 12 columns]

In [13]:
X["Gender"]=X["Gender"].map({
    "Male":1,
    "Female":0
})

X["Married"]=X["Married"].map({
    "Yes":1,
    "NO":0
})

X["Education"]=X["Education"].map({
    "Graduate":1,
    "Not Graduate":0
})

X["Self_Employed"]=X["Self_Employed"].map({
    "Yes":1,
    "No":0
})

X["Dependents"]=X["Dependents"].replace("3+",3)
X["Dependents"]=X["Dependents"].astype(float)

y = y.map({
    "Y":0,
    "N":1
})

In [ ]:
X.isnull()